# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/James-Messinger/eslint-config-modular

extends:
  - modular/node

env:
  jquery: true

globals:
  SwaggerParser: false

  # Google Analytics
  ga: false

  # ACE Editor
  ace: false
